// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

type Group struct {
	name         string
	description  string
	thumbnailUrl string
}

func NewGroup(name, description, thumbnailUrl string) Group {
	return Group{
		name:         name,
		description:  description,
		thumbnailUrl: thumbnailUrl,
	}
}

func (g Group) Render() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"card mt-3 p-3\"><div class=\"row g-0\"><img class=\"col-md-3 img-fluid rounded-start\" style=\"max-height: 200px; object-fit: cover\" src=\"/assets/images/filler.jpeg\"><div class=\"col-md-9\"><div class=\"card-body\"><h5 class=\"card-title\">Group FooBar</h5><p class=\"card-text\">The coolest group of all where all the shit happens</p><a href=\"/groups/1\" class=\"btn btn-success stretched-link\">Open</a></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
