// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

type Movie struct {
	name         string
	description  string
	thumbnailUrl string
	genres       []string
}

func NewMovie(name, description, thumbnailUrl string, genres []string) Movie {
	return Movie{
		name:         name,
		description:  description,
		thumbnailUrl: thumbnailUrl,
		genres:       genres,
	}
}

func (m Movie) Render() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"card g-0 mb-2 p-2\"><div class=\"row justify-content-around\"><img class=\"img-fluid rounded-start col-sm-2 col-5\" src=\"/assets/images/movie_thumbnail.jpeg\" style=\"object-fit: contain; max-height: 250px\"><div class=\"col-sm-10 col-7\"><h5 class=\"card-title\">Group Foo</h5><p class=\"card-text\">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type  and scrambled it to make a type specimen book. It has survive</p><p><span class=\"badge bg-secondary\">Horror</span> <span class=\"badge bg-secondary\">Horror</span> <span class=\"badge bg-secondary\">Horror</span> <span class=\"badge bg-secondary\">Horror</span></p><div class=\"row justify-content-around\"><button type=\"button\" class=\"col-5 col-sm-3 col-md-4 col-lg-3 btn btn-primary\">IMDb</button> <button type=\"button\" class=\"col-5 col-sm-3 col-md-4 ms-1 me-3 btn btn-success\">Select</button></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

type MovieButton struct {
	text string
}
