version: "3.7"

services:
  database:
    container_name: movie_night-database-1
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=movie_night

