CREATE TABLE IF NOT EXISTS movies(
	id SERIAL PRIMARY KEY,
	imdb_link TEXT NOT NULL,
	movie_name TEXT NOT NULL,
	movie_description TEXT NOT NULL,
	rating DECIMAL NOT NULL,
	genres TEXT[],
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
